*&---------------------------------------------------------------------*
*& Include          Z2508R0040_084_SCR
*&---------------------------------------------------------------------*

*SELECTION-SCREEN SKIP.

*SELECTION-SCREEN BEGIN OF LINE.
*
*  SELECTION-SCREEN POSITION 5.
*  SELECTION-SCREEN PUSHBUTTON (30) TEXT-T01 USER-COMMAND BUT1.
*
*SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T02.

  PARAMETERS : P_EKORG TYPE EKKO-EKORG DEFAULT '2000' OBLIGATORY,
               P_EKGRP TYPE EKKO-EKGRP DEFAULT '120' OBLIGATORY,
               P_BUKRS TYPE EKKO-BUKRS DEFAULT '2000' OBLIGATORY,
               P_FILE  TYPE RLGRAP-FILENAME OBLIGATORY.

SELECTION-SCREEN END OF BLOCK B01.
