*&---------------------------------------------------------------------*
*& Include          Z2508R0030_084_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.

  SELECT-OPTIONS: S_BUKRS FOR T001-BUKRS NO INTERVALS NO-EXTENSION OBLIGATORY DEFAULT '4000',
                  S_VBELN  FOR VBAK-VBELN NO INTERVALS NO-EXTENSION OBLIGATORY.

  SELECTION-SCREEN SKIP.

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT 1(10) TEXT-T02 FOR FIELD R1.
    PARAMETERS R1 RADIOBUTTON GROUP RG1 USER-COMMAND RADI.

    SELECTION-SCREEN COMMENT 20(15) TEXT-T03 FOR FIELD R2.
    PARAMETERS R2 RADIOBUTTON GROUP RG1.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B01.
