*&---------------------------------------------------------------------*
*& Include          Z2508R0040_084_SCR
*&---------------------------------------------------------------------*

*SELECTION-SCREEN SKIP.

*SELECTION-SCREEN BEGIN OF LINE.
*
*  SELECTION-SCREEN POSITION 5.
*  SELECTION-SCREEN PUSHBUTTON (30) TEXT-T01 USER-COMMAND BUT1.
*
*SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T02.

  PARAMETERS : P_EKORG TYPE EKKO-EKORG DEFAULT '2000' OBLIGATORY MODIF ID SC1,
               P_EKGRP TYPE EKKO-EKGRP DEFAULT '120' OBLIGATORY MODIF ID SC1,
               P_BUKRS TYPE EKKO-BUKRS DEFAULT '2000' OBLIGATORY MODIF ID SC1,
               P_FILE  TYPE RLGRAP-FILENAME MODIF ID SC1.

SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-T02.
  SELECT-OPTIONS : S_WERKS FOR T001W-WERKS NO INTERVALS NO-EXTENSION OBLIGATORY DEFAULT'2100' MODIF ID SC2, " 플랜트
                S_MATNR FOR MARA-MATNR NO INTERVALS NO-EXTENSION MODIF ID SC2,              " 자재코드
                S_LIFNR FOR LFA1-LIFNR NO INTERVALS NO-EXTENSION MODIF ID SC2,                           " 공급업체
                S_EBELN FOR EKKO-EBELN NO INTERVALS NO-EXTENSION MODIF ID SC2,                           " 구매오더 번호
                S_EBELP FOR EKPO-EBELP NO INTERVALS NO-EXTENSION MODIF ID SC2,                           " 구매오더 품목
                S_BEDAT FOR EKKO-BEDAT NO-EXTENSION MODIF ID SC2,                           " 증빙일
                S_EINDT FOR EKET-EINDT NO INTERVALS NO-EXTENSION MODIF ID SC2.                          " 납품일
  PARAMETERS P_CHECK TYPE C AS CHECKBOX MODIF ID SC2.                        " 체크박스

SELECTION-SCREEN END OF BLOCK B02.

*** 구매오더 생성 / 수정 선택하는 라디오 버튼

SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME .

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT 1(10) TEXT-T03 FOR FIELD R1. " 구매오더생성
    PARAMETERS R1 RADIOBUTTON GROUP RG1 USER-COMMAND RADI .

    SELECTION-SCREEN COMMENT 15(10) TEXT-T04 FOR FIELD R2 . " 구매오더 수정
    PARAMETERS R2 RADIOBUTTON GROUP RG1 DEFAULT 'X'.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B03.
