*&---------------------------------------------------------------------*
*& Include          ZSH08401_TOP
*&---------------------------------------------------------------------*

TABLES : ZS4H084T04.

DATA : GO_CONTAINER TYPE REF TO CL_GUI_DOCKING_CONTAINER,
       GO_ALV_GRID  TYPE REF TO CL_GUI_ALV_GRID.

DATA: BEGIN OF GS_CUST,
        CUST_ID    TYPE ZS4H084T04-CUST_ID,
        CUST_NAME  TYPE ZS4H084T04-CUST_NAME,
        BIRTH_DATE TYPE ZS4H084T04-BIRTH_DATE,
        EMAIL      TYPE ZS4H084T04-EMAIL,
        CNT_RENTAL TYPE I,
        CNT_TOTAL  TYPE I,
      END OF GS_CUST,

      GT_CUST LIKE TABLE OF GS_CUST.


DATA OK_CODE TYPE SY-UCOMM.

DATA: GS_FCAT TYPE LVC_S_FCAT,
      GT_FCAT TYPE LVC_T_FCAT.

DATA GS_LAYOUT TYPE LVC_S_LAYO.

*SCREEN 필드 선언
DATA : S_ID    TYPE ZS4H084T04-CUST_ID,
      S_NAME  TYPE ZS4H084T04-CUST_NAME,
      S_BIRTH TYPE ZS4H084T04-BIRTH_DATE,
      S_EMAIL TYPE ZS4H084T04-EMAIL.

* 수정 시 POPUP 데이터 저장용
DATA : BEGIN OF GS_POPUP,
         CUST_ID    TYPE ZS4H084T04-CUST_ID,
         CUST_NAME  TYPE ZS4H084T04-CUST_NAME,
         BIRTH_DATE TYPE ZS4H084T04-BIRTH_DATE,
         EMAIL      TYPE ZS4H084T04-EMAIL,
       END OF GS_POPUP.

* 도서정보 팝업창 데이터 채우기
DATA : BEGIN OF GS_POPUP2,
         ISBN   TYPE C LENGTH 16,             " ISBN + SEQ
         BNAME  TYPE ZS4H084T02-BNAME,        " 도서명
         RDATE  TYPE ZS4H084T05-RDATE,        " 대여일
         RTDATE TYPE ZS4H084T05-RTDATE,       " 반납일
       END OF GS_POPUP2,
       GT_POPUP2 LIKE TABLE OF GS_POPUP2.

DATA : GO_CONTAINER2 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
       GO_ALV_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA: GS_FCAT2 TYPE LVC_S_FCAT,
      GT_FCAT2 TYPE LVC_T_FCAT,
      GS_LAYOUT2 TYPE LVC_S_LAYO.

* 성공 여부 저장.
DATA : GV_STATUS  TYPE C.

* 팝업 종류 설정
DATA : GV_POP TYPE C.
