*&---------------------------------------------------------------------*
*& Include          ZSH08401_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T04.

    SELECTION-SCREEN SKIP.

  SELECTION-SCREEN BEGIN OF LINE.

    SELECTION-SCREEN COMMENT 1(5) TEXT-T01 FOR FIELD R1.  " 조회
    PARAMETERS: R1 RADIOBUTTON GROUP RG1 USER-COMMAND RADI DEFAULT 'X'. " USER-COMMAND 입력하면 누를때마다 AT SELECTION SCREEN OUTPUT 탐.

    SELECTION-SCREEN COMMENT 15(5) TEXT-T02 FOR FIELD R2. " 생성
    PARAMETERS: R2 RADIOBUTTON GROUP RG1.

    SELECTION-SCREEN COMMENT 30(5) TEXT-T03 FOR FIELD R3. " 변경
    PARAMETERS: R3 RADIOBUTTON GROUP RG1.

  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B01.



SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-T05.

  SELECT-OPTIONS :  SO_NAME FOR GS_CUST-CUST_NAME NO INTERVALS NO-EXTENSION MODIF ID SO,
                    SO_ID   FOR GS_CUST-CUST_ID MODIF ID SO.

  SELECTION-SCREEN END OF BLOCK B02.
